### ISSUE TITLE
learning_to_simulate=> failed to train 

### ISSUE THREAD

**Issue by vardhah** [deepmind/deepmind-research#112]
I tried to run the code on Ubuntu18 . Got this error: 

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 281, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/home/hv/learning_to_simulate/train.py", line 133
    out_dict = {**context}
                 ^
SyntaxError: invalid syntax

if possible guide me where I am doing wrong. I checked all the version requirements and other dependencies. Thanks

**Comment by abdelabdalla** [comment]
Hello, I'm running into this issue and was wondering how you got it to work (I assume you got it working as you have closed the issue).
