### ISSUE TITLE
Two issues about ogb_lsc mag

### ISSUE THREAD

**Issue by cfangplus** [deepmind/deepmind-research#258]
hi,

I ran this script  https://github.com/deepmind/deepmind-research/blob/master/ogb_lsc/mag/run_training.sh and found two issues.

1, ran script with the jaxline _mode be 'train' and an attibuteError was thrown, the detail is list as follow:
Traceback (most recent call last):
  File "/home/fc/pythonws/mag240m/deepmind/experiment.py", line 725, in <module>
    app.run(lambda argv: main(argv, Experiment))
  File "/root/miniconda3/envs/deepmind/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/root/miniconda3/envs/deepmind/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/fc/pythonws/mag240m/deepmind/experiment.py", line 725, in <lambda>
    app.run(lambda argv: main(argv, Experiment))
  File "/home/fc/pythonws/mag240m/deepmind/experiment.py", line 717, in main
    platform.main(experiment_class, argv)
  File "/root/miniconda3/envs/deepmind/lib/python3.7/site-packages/jaxline/utils.py", line 401, in inner_wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/deepmind/lib/python3.7/site-packages/jaxline/platform.py", line 126, in main
    train.train(experiment_class, config, checkpointer, writer)
  File "/root/miniconda3/envs/deepmind/lib/python3.7/site-packages/jaxline/utils.py", line 529, in inner_wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/deepmind/lib/python3.7/site-packages/jaxline/train.py", line 118, in train
    experiment.train_loop(config, state, periodic_actions, writer)
  File "/root/miniconda3/envs/deepmind/lib/python3.7/site-packages/jaxline/experiment.py", line 156, in train_loop
    global_step=global_step_devices, rng=step_key, writer=writer)
  File "/home/fc/pythonws/mag240m/deepmind/experiment.py", line 221, in step
    self._train_init()
  File "/home/fc/pythonws/mag240m/deepmind/experiment.py", line 184, in _train_init
    dummy_batch = next(self._train_input)
  File "/root/miniconda3/envs/deepmind/lib/python3.7/site-packages/jaxline/utils.py", line 134, in py_prefetch
    raise producer_error[0]
  File "/root/miniconda3/envs/deepmind/lib/python3.7/site-packages/jaxline/utils.py", line 115, in producer
    for item in iterable:
  File "/home/fc/pythonws/mag240m/deepmind/datasets.py", line 143, in build_dataset_iterator
    **online_subsampling_kwargs)
  File "/home/fc/pythonws/mag240m/deepmind/data_utils.py", line 289, in get_graph_subsampling_dataset
    output_signature=utils_tf.specs_from_graphs_tuple(sample_graph))
  File "/root/miniconda3/envs/deepmind/lib/python3.7/site-packages/graph_nets/utils_tf.py", line 1160, in specs_from_graphs_tuple
    shape = list(field_sample.shape)
AttributeError: 'dict' object has no attribute 'shape'

2, ran script with the jaxline_mode be 'train_eval_multithreaded' and  an error called 'Checkpoint None invalid or already evaluated, waiting' was thrown from the main thread.

Please help to check the two issues.

**Comment by alvarosg** [comment]
Thanks for your comment:

1. Could you try updating the graph nets library to the latest version in github, `pip install git+git://github.com/deepmind/graph_nets.git@64771dff0d74ca8e77b1f1dcd5a7d26634356d61`?

2. This message is expected, this happens because training is failing, so the eval worker in a separate thread cannot find trained weights.

**Comment by cfangplus** [comment]
yea, that's right, after I update the graph nets library, the error disappeared.
