### ISSUE TITLE
Problem with hierarchical_transformer_memory

### ISSUE THREAD

**Issue by sunchipsster1** [deepmind/deepmind-research#291]
Hello, I am trying out the hierarchical transformer memory. When running the htm_attention_test.py on the provided sample inputs, I encounter the following problem. Do you know what is going on and why it is unable to run even on the simple setup with **dummy queries and memories** (eg. as provided -- queries = np.random.random([batch_size, query_length, embedding_size]))?

Many thanks! :) 

Traceback below: 

Traceback (most recent call last):
  File "htm_attention_test.py", line 144, in <module>
    absltest.main()
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/absl/testing/absltest.py", line 2065, in main
    _run_in_app(run_tests, args, kwargs)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/absl/testing/absltest.py", line 2182, in _run_in_app
    app.run(main=main_function)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/absl/testing/absltest.py", line 2180, in main_function
    function(argv, args, kwargs)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/absl/testing/absltest.py", line 2577, in run_tests
    argv, args, kwargs, xml_reporter.TextAndXMLTestRunner)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/absl/testing/absltest.py", line 2545, in _run_and_get_tests_result
    test_program = unittest.TestProgram(*args, **kwargs)
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/miniconda/3/lib/python3.7/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/miniconda/3/lib/python3.7/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/absl/testing/_pretty_print_reporter.py", line 87, in run
    return super(TextTestRunner, self).run(test)
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/miniconda/3/lib/python3.7/unittest/runner.py", line 176, in run
    test(result)
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/miniconda/3/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/miniconda/3/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/miniconda/3/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/miniconda/3/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/miniconda/3/lib/python3.7/unittest/case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "/cvmfs/ai.mila.quebec/apps/x86_64/debian/miniconda/3/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/absl/testing/parameterized.py", line 314, in bound_param_test
    return test_method(self, **testcase_params)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/haiku/_src/test_utils.py", line 106, in wrapper
    out, state = apply(params, state, rng)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/haiku/_src/transform.py", line 313, in apply_fn
    out = f(*args, **kwargs)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/haiku/_src/test_utils.py", line 101, in <lambda>
    init, apply = transform.transform_with_state(lambda: f(*a, **k))
  File "htm_attention_test.py", line 95, in test_output_shapes
    results = hm_att(queries, memory)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/haiku/_src/module.py", line 428, in wrapped
    out = f(*args, **kwargs)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/haiku/_src/module.py", line 279, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/hierarchical_attention/htm_attention.py", line 216, in __call__
    top_k_indices) #batch_within_memory_attention
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/jax/_src/api.py", line 1292, in batched_fun
    ).call_wrapped(*args_flat)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/hierarchical_attention/htm_attention.py", line 202, in _within_memory_attention
    attention_results = do_attention(sub_inputs, top_k_contents)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/jax/_src/api.py", line 1292, in batched_fun
    ).call_wrapped(*args_flat)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/hierarchical_attention/htm_attention.py", line 199, in do_attention
    value=sub_sub_top_k_contents)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/haiku/_src/module.py", line 428, in wrapped
    out = f(*args, **kwargs)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/haiku/_src/module.py", line 279, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/haiku/_src/attention.py", line 80, in __call__
    attn_vec = jnp.reshape(attn, (*value.shape[:-1], -1))
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 1711, in reshape
    return a.reshape(newshape, order=order)  # forward to method for ndarrays
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 1729, in _reshape
    newshape = _compute_newshape(a, args[0] if len(args) == 1 else args)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 1725, in _compute_newshape
    for d in newshape)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 1725, in <genexpr>
    for d in newshape)
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/jax/core.py", line 1396, in divide_shape_sizes
    return handler.divide_shape_sizes(ds[:len(s1)], ds[len(s1):])
  File "/home/mila/c/chen.sun/deepmind-research/hierarchical_transformer_memory/htm_env/lib/python3.7/site-packages/jax/core.py", line 1311, in divide_shape_sizes
    raise InconclusiveDimensionOperation(f"Cannot divide evenly the sizes of shapes {tuple(s1)} and {tuple(s2)}")
**jax._src.traceback_util.UnfilteredStackTrace: jax.core.InconclusiveDimensionOperation: Cannot divide evenly the sizes of shapes (4, 1, 3, 4) and (4, 5, -1)**

**Comment by diegolascasas** [comment]
Version 0.0.5 should has the bugfix, so installing it from pip should be working now.
https://github.com/deepmind/dm-haiku/releases/tag/v0.0.5

**Comment by sunchipsster1** [comment]
Thank you @diegolascasas it works well now! :) have a great day!
