### ISSUE TITLE
curl for omniglot not working

### ISSUE THREAD

**Issue by dhanajitb** [deepmind/deepmind-research#31]
When I ran
`PYTHONPATH=`pwd`/..:$PYTHONPATH python3 train_main.py --dataset='omniglot'`
It gave the following error:
`Traceback (most recent call last):
  File "train_main.py", line 79, in <module>
    app.run(main)
  File "/data1/dhanajit/anaconda3/envs/curl/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/data1/dhanajit/anaconda3/envs/curl/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train_main.py", line 75, in main
    use_supervised_replay=False,
  File "/data1/dhanajit/Projects/2020/deepmind-research/curl/training.py", line 555, in run_training
    n_concurrent_classes, image_key, label_key)
  File "/data1/dhanajit/Projects/2020/deepmind-research/curl/training.py", line 129, in get_data_sources
    **dataset_kwargs)
TypeError: FunctionWrapper object got multiple values for keyword argument 'split`

**Comment by saehoonkim** [comment]
I have the same issue for running omniglot. It seems that tfds in tf 1.14 doesn't support omniglot in this setting.

**Comment by drao2** [comment]
Thanks for raising this issue. I'm looking into it and hope to have a fix in the next few days.

**Comment by drao2** [comment]
This should now be fixed.

**Comment by dhanajitb** [comment]
Yes, it's working now.
