### ISSUE TITLE
meshgraphnets : training cylinder_flow gives InvalidArgumentError 

### ISSUE THREAD

**Issue by nailimixaM** [deepmind/deepmind-research#321]
## Description of the bug

Hi @tobiaspfaff, @alvarosg & team, thanks for making this repo - I'm hoping to use the meshgraphnets on some real combustion CFD data as discussed with Tobi. However, I'm encountering a bug during training of the `cylinder_flow` test case without any modifications. In a clean cloned repo, running the command: 
`python -m meshgraphnets.run_model --mode=train --model=cfd --checkpoint_dir=${DATA}/chk --dataset_dir=${DATA}/cylinder_flow`

gives the following error:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot update variable with shape [3] using a Tensor with shape [2], shapes must be equal.
         [[{{node Model/loss/output_normalizer/cond/AssignAddVariableOp_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mlc70/tmp/deepmind-research/meshgraphnets/run_model.py", line 131, in <module>
    app.run(main)
  File "/home/mlc70/tmp/dmenv/lib/python3.6/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/mlc70/tmp/dmenv/lib/python3.6/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/mlc70/tmp/deepmind-research/meshgraphnets/run_model.py", line 126, in main
    learner(model, params)
  File "/home/mlc70/tmp/deepmind-research/meshgraphnets/run_model.py", line 83, in learner
    _, step, loss = sess.run([train_op, global_step, loss_op])
  File "/home/mlc70/tmp/dmenv/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/mlc70/tmp/dmenv/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/home/mlc70/tmp/dmenv/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/home/mlc70/tmp/dmenv/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/mlc70/tmp/dmenv/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/home/mlc70/tmp/dmenv/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "/home/mlc70/tmp/dmenv/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "/home/mlc70/tmp/dmenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/mlc70/tmp/dmenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/mlc70/tmp/dmenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/mlc70/tmp/dmenv/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot update variable with shape [3] using a Tensor with shape [2], shapes must be equal.
         [[node Model/loss/output_normalizer/cond/AssignAddVariableOp_1 (defined at home/mlc70/tmp/dmenv/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
```

## Notes
- Training `flag_simple` works fine

## System info:
System: Linux
Node Name: paragon
Release: 4.15.0-159-generic
Version: #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021
Machine: x86_64
Processor: x86_64
GPU: NVIDIA Quadro P400

## Packages                
absl-py                1.0.0
astor                  0.8.1
cloudpickle            1.1.1
contextlib2            21.6.0
cycler                 0.11.0
dataclasses            0.8
decorator              5.1.1
dm-sonnet              1.36
gast                   0.2.2
google-pasta           0.2.0
GPUtil                 1.4.0
grpcio                 1.43.0
h5py                   2.10.0
importlib-metadata     4.8.3
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.2
kiwisolver             1.3.1
Markdown               3.3.6
matplotlib             3.3.4
numpy                  1.18.5
opt-einsum             3.3.0
Pillow                 8.4.0
pip                    21.3.1
pkg_resources          0.0.0
protobuf               3.19.3
psutil                 5.9.0
pyparsing              3.0.6
python-dateutil        2.8.2
semantic-version       2.8.5
setuptools             59.6.0
six                    1.16.0
tabulate               0.8.9
tensorboard            1.15.0
tensorflow-estimator   1.15.1
tensorflow-gpu         1.15.5
tensorflow-probability 0.8.0
termcolor              1.1.0
typing_extensions      4.0.1
Werkzeug               2.0.2
wheel                  0.37.1
wrapt                  1.13.3
zipp                   3.6.0

**Comment by nailimixaM** [comment]
Solution: bug was due to checkpoint directory being shared between two different test cases (flag_simple and cylinder_flow). When training different models, ensure the checkpoint directories are unique, like `--checkpoint_dir=${DATA}/chk_cylinder` and `--checkpoint_dir=${DATA}/chk_flag`
