### ISSUE TITLE
tensorflow has no attribute GraphKeys

### ISSUE THREAD

**Issue by JPFrancis** [deepmind/deepmind-research#46]
Hi, not urgent, but I am attempting to reproduce the results by running the 'run.sh' script and hitting the error 'tensorflow' has no attribute 'GraphKeys'. 

I think this was handled in the quick_eval_cifar.py tensorflow.compat.v1 import but not in the clever_hans scripts from which the error originates. Not sure how to best proceed. Traceback as follows. Any help would be appreciated.

Traceback (most recent call last):
  File "/home/jpfrancis/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jpfrancis/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jpfrancis/Development/deepmind-research/unsupervised_adversarial_training/quick_eval_cifar.py", line 30, in <module>
    from cleverhans import attacks
  File "/home/jpfrancis/anaconda3/lib/python3.7/site-packages/cleverhans/attacks/__init__.py", line 9, in <module>
    from cleverhans.attacks_tf import SPSAAdam, margin_logit_loss, TensorAdam
  File "/home/jpfrancis/anaconda3/lib/python3.7/site-packages/cleverhans/attacks_tf.py", line 17, in <module>
    from cleverhans import utils_tf
  File "/home/jpfrancis/anaconda3/lib/python3.7/site-packages/cleverhans/utils_tf.py", line 341, in <module>
    loss_collection=tf.GraphKeys.REGULARIZATION_LOSSES):
AttributeError: module 'tensorflow' has no attribute 'GraphKeys'

**Comment by diegolascasas** [comment]
Hi @JPFrancis,
Which version of tensorflow are you using?

**Comment by MicroscapeInc** [comment]
Hey, thanks for the reply. This is tensorflow-gpu 1.8.0. Should I upgrade?

**Comment by JPFrancis** [comment]
Apologies, I was on a company account. The above stands. Thanks
