### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by leonaardaa** [deepmind/deepmind-research#52]
After running main.py with all dependencies installed, I get a MemoryError

I0526 16:25:56.645768 140080367834880 session_manager.py:502] Done running local_init_op.
Traceback (most recent call last):
  File "main.py", line 200, in <module>
    app.run(main)
  File "/home/leonarda/.local/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/leonarda/.local/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 180, in main
    with tf.train.MonitoredSession(hooks=hooks) as sess:
  File "/home/leonarda/.local/lib/python2.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1014, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/leonarda/.local/lib/python2.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 725, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/leonarda/.local/lib/python2.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1207, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/leonarda/.local/lib/python2.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1212, in _create_session
    return self._sess_creator.create_session()
  File "/home/leonarda/.local/lib/python2.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 885, in create_session
    hook.after_create_session(self.tf_sess, self.coord)
  File "/home/leonarda/.local/lib/python2.7/site-packages/tensorflow_core/python/training/basic_session_run_hooks.py", line 572, in after_create_session
    self._checkpoint_dir, "graph.pbtxt")
  File "/home/leonarda/.local/lib/python2.7/site-packages/tensorflow_core/python/framework/graph_io.py", line 72, in write_graph
    graph_def, float_format=''))
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 197, in MessageToString
    printer.PrintMessage(message)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 462, in PrintMessage
    self.PrintField(field, element)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 557, in PrintField
    self.PrintFieldValue(field, value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 604, in PrintFieldValue
    self._PrintMessageFieldValue(value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 589, in _PrintMessageFieldValue
    self.PrintMessage(value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 454, in PrintMessage
    self.PrintField(field, entry_submsg)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 557, in PrintField
    self.PrintFieldValue(field, value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 604, in PrintFieldValue
    self._PrintMessageFieldValue(value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 589, in _PrintMessageFieldValue
    self.PrintMessage(value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 464, in PrintMessage
    self.PrintField(field, value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 557, in PrintField
    self.PrintFieldValue(field, value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 604, in PrintFieldValue
    self._PrintMessageFieldValue(value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 589, in _PrintMessageFieldValue
    self.PrintMessage(value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 464, in PrintMessage
    self.PrintField(field, value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 557, in PrintField
    self.PrintFieldValue(field, value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 604, in PrintFieldValue
    self._PrintMessageFieldValue(value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 589, in _PrintMessageFieldValue
    self.PrintMessage(value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 464, in PrintMessage
    self.PrintField(field, value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 557, in PrintField
    self.PrintFieldValue(field, value)
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 622, in PrintFieldValue
    out.write(text_encoding.CEscape(out_value, out_as_utf8))
  File "/home/leonarda/.local/lib/python2.7/site-packages/google/protobuf/text_encoding.py", line 85, in CEscape
    return ''.join(_cescape_byte_to_str[ord_(c)] for c in text)
MemoryError

I'm not sure what is the problem since I'm using everythig as it's supposed to be.

**Comment by diegolascasas** [comment]
Hi @leonaardaa, 

Which project are you trying to run?
And can you provide more information about your system?
