### ISSUE TITLE
Errors about glassy_dynamics

### ISSUE THREAD

**Issue by MaoYuwei** [deepmind/deepmind-research#60]
Hi, I am interested in this paper, and thank you for your code. 
I got errors when I run the code. Can you give me help about that? Thanks very much.
When I run the train_test.py, it shows that :
======================================================================
ERROR: test_apply_model (__main__.TensorflowTrainTest)
Tests if we can apply a model to a small test dataset.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ymt1957/glassy_dynamics/train_test.py", line 130, in test_apply_model
    time_index=0)
  File "/home/ymt1957/glassy_dynamics/train.py", line 351, in apply_model
    saver = tf.train.import_meta_graph(checkpoint_path + '.meta')
  File "/home/ymt1957/anaconda3/envs/glass_dynamics/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1435, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/home/ymt1957/anaconda3/envs/glass_dynamics/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1457, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/home/ymt1957/anaconda3/envs/glass_dynamics/lib/python3.5/site-packages/tensorflow/python/framework/meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/home/ymt1957/anaconda3/envs/glass_dynamics/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ymt1957/anaconda3/envs/glass_dynamics/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 399, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/home/ymt1957/anaconda3/envs/glass_dynamics/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 159, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'SelectV2'

----------------------------------------------------------------------
Ran 8 tests in 7.955s

FAILED (errors=1, skipped=2)

Process finished with exit code 1

**Comment by jx291605427** [comment]
I got the same trouble. Have you fixed that??

**Comment by jx291605427** [comment]
I fixed it by using a trained model of myself.

**Comment by thomaskeck** [comment]
Thanks for reporting this issue.

It looks like we included the wrong tensorflow version in our requirements file.
Please try the following dependencies:
`
# GlassyDynamics
absl-py==0.8.1
astor==0.8.0
cloudpickle==1.1.1
contextlib2==0.6.0.post1
decorator==4.4.0
dm-sonnet==1.35
future==0.18.0
gast==0.2.2
google-pasta==0.1.7
graph-nets==1.0.4
grpcio==1.24.1
h5py==2.10.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.1.1
mock==3.0.5
networkx==2.3
numpy==1.17.2
protobuf==3.10.0
semantic-version==2.8.2
six==1.12.0
tensorboard==1.15.0
tensorflow==1.15.0
tensorflow-estimator==1.15.1
tensorflow-probability==0.7.0
termcolor==1.1.0
Werkzeug==0.16.0
wrapt==1.11.2
`

In my local setup those dependencies are compatible with one another and allow to run the unittests.
We will update the repository soon.
