### ISSUE TITLE
Error generated while executing 

### ISSUE THREAD

**Issue by geet2019** [deepmind/deepmind-research#70]
File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Traceback (most recent call last):
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Traceback (most recent call last):
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Traceback (most recent call last):
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Traceback (most recent call last):
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Traceback (most recent call last):
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Traceback (most recent call last):
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Traceback (most recent call last):
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
    return _run_code(code, main_globals, None,
    return _run_code(code, main_globals, None,
    return _run_code(code, main_globals, None,
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    return _run_code(code, main_globals, None,
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
  File "/home/geethu/deepmind_research/alphafold_casp13/contacts.py", line 21, in <module>
    exec(code, run_globals)
  File "/home/geethu/deepmind_research/alphafold_casp13/contacts.py", line 21, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'
    exec(code, run_globals)
    from absl import app
  File "/home/geethu/deepmind_research/alphafold_casp13/contacts.py", line 21, in <module>
ModuleNotFoundError: No module named 'absl'
    from absl import app
    exec(code, run_globals)
  File "/home/geethu/deepmind_research/alphafold_casp13/contacts.py", line 21, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'
ModuleNotFoundError: No module named 'absl'
    return _run_code(code, main_globals, None,
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/geethu/deepmind_research/alphafold_casp13/contacts.py", line 21, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'
Traceback (most recent call last):
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
    return _run_code(code, main_globals, None,
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/geethu/deepmind_research/alphafold_casp13/contacts.py", line 21, in <module>
    return _run_code(code, main_globals, None,
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    from absl import app
    exec(code, run_globals)
ModuleNotFoundError: No module named 'absl'
  File "/home/geethu/deepmind_research/alphafold_casp13/contacts.py", line 21, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'
  File "/home/geethu/deepmind_research/alphafold_casp13/contacts.py", line 21, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'
    exec(code, run_globals)
  File "/home/geethu/deepmind_research/alphafold_casp13/contacts.py", line 21, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'
Ensembling all replica outputs
Traceback (most recent call last):
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/geethu/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/geethu/deepmind_research/alphafold_casp13/ensemble_contact_maps.py", line 24, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'

Created a folder - deepmind inside alphafold_casp13(dataset)and run_eval.sh file - Is it ok ? running from inside deepmind

**Comment by Augustin-Zidek** [comment]
Hi, sorry for taking a while to reply. Are you still seeing this error or did you manage to get it working?

It seems like `absl` was not installed correctly. Did you follow the steps in https://github.com/deepmind/deepmind-research/tree/master/alphafold_casp13#running-the-system? 

Note that it is important to run the `run_eval.sh` script from the `deepmin-research` root directory (i.e. running `alphafold_casp13/run_eval.sh` will work while running `run_eval.sh` inside `alphafold_casp13/` won't).
