### ISSUE TITLE
Evaluating AlphaFold using Windows 10, WSL and Ubuntu

### ISSUE THREAD

**Issue by OneWorld-github** [deepmind/deepmind-research#75]
Hi, I'm a beginner trying to get AlphaFold to work in Windows 10.
I have WSL enabled and Ubuntu installed.

I tried to run the script with the requirements, and ran into problems, so I installed each python package individually in my virtual environment, and then commented out the packages in the requirements file, so that it would get past this stage.

I then ran the bash script in Windows Command Prompt using this command, and received the following error traceback in my command prompt.   

    `bash alphafold_casp13/run_eval.sh`

    `(alphafold_env) C:\Users\....\deepmind-research-master>bash alphafold_casp13/run_eval.sh
    Collecting wheel Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
    Installing collected packages: wheel
    Successfully installed wheel-0.35.1
    Saving output to /home/user/contacts_T1019s2_2020_09_06_12_10_32/
    Launching all models for replica 0
    Launching all models for replica 1
    Launching all models for replica 2
    Launching all models for replica 3
    All models running, waiting for them to complete
    Traceback (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    Traceback (most recent call last):
    Traceback (most recent call last):
    File "/mnt/c/Users/..../deepmind-research-master/alphafold_casp13/contacts.py", line 21, in <module>
    File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    Traceback (most recent call last):
      return _run_code(code, main_globals, None,
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
      return _run_code(code, main_globals, None,
    exec(code, run_globals)
    exec(code, run_globals)
    File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    File "/mnt/c/Users/..../deepmind-research-master/alphafold_casp13/contacts.py", line 21, in <module>
    File "/mnt/c/Users/....g/deepmind-research-master/alphafold_casp13/contacts.py", line 21, in <module>
      exec(code, run_globals)
    File "/mnt/c/Users/..../deepmind-research-master/alphafold_casp13/contacts.py", line 21, in <module>
    Traceback (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
      return _run_code(code, main_globals, None,
    from absl import app
    File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    from absl import app
    from absl import app
    from absl import app
    ModuleNotFoundError: No module named 'absl'
      exec(code, run_globals) 
    ModuleNotFoundError: No module named 'absl'
    ModuleNotFoundError: No module named 'absl'
    Traceback (most recent call last):
    ModuleNotFoundError: No module named 'absl'
      File "/mnt/c/Users/..../deepmind-research-master/alphafold_casp13/contacts.py", line 21, in <module>
    Traceback (most recent call last):
    Traceback (most recent call last):
      File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    from absl import app
    File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
      return _run_code(code, main_globals, None,
    ModuleNotFoundError: No module named 'absl'
      return _run_code(code, main_globals, None,
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    Traceback (most recent call last):
      exec(code, run_globals)
      exec(code, run_globals)
    File "/mnt/c/Users/..../deepmind-research-master/alphafold_casp13/contacts.py", line 21, in <module>
    File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    File "/mnt/c/Users/..../deepmind-research-master/alphafold_casp13/contacts.py", line 21, in <module>
    File "/mnt/c/Users/..../deepmind-research-master/alphafold_casp13/contacts.py", line 21, in <module>
    from absl import app
      return _run_code(code, main_globals, None,
    from absl import app
    ModuleNotFoundError: No module named 'absl'
      from absl import app
    File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    ModuleNotFoundError: No module named 'absl'
    ModuleNotFoundError: No module named 'absl'
      exec(code, run_globals)
    File "/mnt/c/Users/..../deepmind-research-master/alphafold_casp13/contacts.py", line 21, in <module>
    from absl import app
    ModuleNotFoundError: No module named 'absl'
    Ensembling all replica outputs
    Traceback (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
    File "/mnt/c/Users/..../deepmind-research-master/alphafold_casp13/ensemble_contact_maps.py", line 24, in <module>
    from absl import app
    ModuleNotFoundError: No module named 'absl'

    (alphafold_env) C:\....\deepmind-research-master>`

I have Python 3.6 installed on my machine.  But I used to have python 3.8 installed.  I uninstalled python 3.8 from my machine.  So not sure why Python 3.8 is in the traceback.

`(alphafold_env) C:\....\deepmind-research-master>python --version
Python 3.6.4`

Is it possible that when I run this run_eval bash script in windows command prompt, it finds the version of Python 3.8 that was installed in Windows, still in Ubuntu ?

I was wondering if anyone has a walkthrough for beginners to AlphaFold that use Windows 10 ?

Or if there are any other suggestions regarding how I could get AlphaFold running, that would be much appreciated.

**Comment by OneWorld-github** [comment]
I actually got passed this error doing this...

I did this by uninstalling any version of python other than version 3.6 on my system.

I then uninstalled ubuntu from the Microsoft Store, and reinstalled ubuntu 18.04 from the Microsoft store.

Then run this command in the ubuntu linux command line:

`sudo apt-get install python3-venv`


I then ran

`bash alphafold_casp13/run_eval.sh`

which downloads the libraries from internet and installs them.

and got this error message:-

`Collecting grpcio>=1.8.6 (from tensorflow==1.14->-r alphafold_casp13/requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/e3/0e/f56aa1f8200ae3c5d38305e69f5920caa480c7ff54ae4d8a5f57d1d69fa4/grpcio-1.31.0.tar.gz (20.0MB)
    100% |████████████████████████████████| 20.0MB 79kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fnozvtho/grpcio/setup.py", line 197, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-build-fnozvtho/grpcio/setup.py", line 157, in check_linker_need_libatomic
        stderr=PIPE)
      File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cc': 'cc'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fnozvtho/grpcio/`

**Comment by OneWorld-github** [comment]
So I tried

`sudo apt install python3-pip`

in the ubuntu terminal, to see if the package manager there needed an update to get it to work.

and reran this script, in the windows terminal

`bash alphafold_casp13/run_eval.sh`

and this did indeed work...

`
I0906 17:21:43.850929 140638077060928 contacts.py:81] Writing output to /home/user/contacts_T1019s2_2020_09_06_17_17_42/distogram/2
I0906 17:21:43.902758 140638077060928 contacts.py:114] Eval config is {'crop_shingle_x': 16, 'crop_shingle_y': 16, 'eval_sstable': 'alphafold_casp13/T1019s2/T1019s2.tfrec', 'max_num_examples': 500, 'output_path': '/home/user/contacts_T1019s2_2020_09_06_17_17_42/distogram/2', 'pyramid_weights': 0.75, 'save_rr_files': True, 'stats_file': 'alphafold_casp13/873731/stats_train_s35.json'}
num_bins: 64
I0906 17:21:45.237473 139822654359360 contacts.py:191] SepWorking on 0 T1019s2-l64_s24 T1019s2 64
I0906 17:21:45.276877 139822654359360 contacts.py:194] Getting residue_index from features
I0906 17:21:45.674456 140638077060928 contacts.py:191] SepWorking on 0 T1019s2-l64_s24 T1019s2 64
I0906 17:21:45.773195 140638077060928 contacts.py:194] Getting residue_index from features

`

hmm how do I access 

/home/user/contacts_T1019s2_2020_09_06_17_17_42/distogram/2 

from windows, if it is running Ubuntu through WSL ?

**Comment by OneWorld-github** [comment]
My system has a single NVidia 1070 GTX GPU (8GB ram), and it is running Alpha Fold seemingly slowly, and seems to freeze other operations in Windows.  Wondering if this is because I'm not using a fast enough GPU or whether this Windows, Ubuntu, WSL setup introduces some bottlenecks ???

How long should it take to run the run_eval.sh script on an NVidia 1070 GTX GPU with 8GB ram ?

**Comment by Augustin-Zidek** [comment]
I am glad you managed to resolve most of your issues.

> Wondering if this is because I'm not using a fast enough GPU or whether this Windows, Ubuntu, WSL setup introduces some bottlenecks ???

We tested AlphaFold only under Linux, so it is probable there is some performance issue when running it under WSL. It is even possible that TensorFlow can't use the GPU you have because it is running through WSL. I strongly recommend running AlphaFold on a Linux machine.

> How long should it take to run the run_eval.sh script on an NVidia 1070 GTX GPU with 8GB ram ?
Which sequence are you running AlphaFold on? On a short sequence I would expect about 30-60 minutes. On a longer sequence a few hours.

> Is this machine fit for the purpose of evaluating Alpha Fold ? Or are there any alternatives you could suggest ?
The machine specs look fine. As I said above, I would just recommend running AlphaFold under Linux and not through WSL as it can cause all kinds of weird performance issues.

**Comment by OneWorld-github** [comment]
Thank you for your feedback Augustin.  I was just running the run_eval script as provided on github.

I will run the process again in windows, and check NVidia inspector, and report this here.

I have a dual boot with Ubuntu installed.  Though I think it's on a disc drive, so might be a bit slower.  Will give it a go, and report here how this goes also.
